#requires -Version 5.1
# setup-lumo.ps1 — stand up the Lumo coding stack on Windows.
#   opencode (Claude-Code-style TUI)  ->  lumo-tamer (local OpenAI proxy :3003)  ->  Proton Lumo
#
# Idempotent: re-running updates the build/configs but KEEPS your generated API key and auth vault.
# Prereqs (scoop/winget): git, nodejs, go, opencode.  (scoop install opencode go ; winget = OpenJS.NodeJS.LTS)
#
#   pwsh ~\.config\bootstrap\setup-lumo.ps1
#   then, once per machine:  cd ~\lumo-tamer ; tamer auth login
$ErrorActionPreference = 'Stop'
function Log($m){ Write-Host "[lumo] $m" -ForegroundColor Cyan }
function Die($m){ Write-Host "[lumo] $m" -ForegroundColor Red; exit 1 }

$repo  = if ($env:LUMO_TAMER_REPO) { $env:LUMO_TAMER_REPO } else { 'https://github.com/ZeroTricks/lumo-tamer.git' }
$dir   = Join-Path $HOME 'lumo-tamer'
$ocDir = Join-Path $HOME '.config\opencode'

foreach ($bin in 'git','node','npm','go') { if (-not (Get-Command $bin -EA SilentlyContinue)) { Die "missing '$bin' (scoop install it first)" } }

# 1. clone or update
if (Test-Path (Join-Path $dir '.git')) { Log "updating $dir"; git -C $dir pull --ff-only 2>$null }
else { Log "cloning lumo-tamer -> $dir"; git clone $repo $dir }

# 2. build + link global `tamer`
Log 'building (npm install + build:all)…'
Push-Location $dir
npm install --silent
npm run --silent build:all
try { npm link 2>$null | Out-Null } catch { Log 'npm link skipped (use: node dist/src/tamer.js)' }
Pop-Location

# 3. reuse existing key or generate one (never committed to git)
$cfg = Join-Path $dir 'config.yaml'
$key = $null
if (Test-Path $cfg) { $m = Select-String -Path $cfg -Pattern 'apiKey:\s*"([^"]+)"' | Select-Object -First 1; if ($m) { $key = $m.Matches[0].Groups[1].Value } }
if (-not $key) { $key = 'lt-' + -join ((1..24) | ForEach-Object { '{0:x2}' -f (Get-Random -Maximum 256) }) }

# 4. lumo-tamer config.yaml
Log "writing $cfg"
@"
# Generated by setup-lumo.ps1. Overrides config.defaults.yaml (defaults are source of truth).
auth:
  method: "login"
  autoRefresh:
    enabled: true
    intervalHours: 8
server:
  port: 3003
  apiKey: "$key"
  defaultModelTier: "auto"
  customTools:
    enabled: true
  enableWebSearch: true
"@ | Set-Content -Path $cfg -Encoding utf8

# 5. opencode provider config + global agent rules
New-Item -ItemType Directory -Force -Path $ocDir | Out-Null
Log "writing $ocDir\opencode.json"
@"
{
  "`$schema": "https://opencode.ai/config.json",
  "provider": {
    "ollama": {
      "name": "Ollama (local)",
      "npm": "@ai-sdk/openai-compatible",
      "options": { "baseURL": "http://localhost:11434/v1", "apiKey": "ollama" },
      "models": { "qwen2.5-coder": { "name": "Qwen 2.5 Coder (7.6B Q4)" } }
    },
    "lumo-tamer": {
      "name": "Lumo (Proton, via lumo-tamer)",
      "npm": "@ai-sdk/openai-compatible",
      "options": { "baseURL": "http://localhost:3003/v1", "apiKey": "$key" },
      "models": { "lumo": { "name": "Lumo (auto)" }, "lumo-max": { "name": "Lumo 2.0 Max" }, "lumo-lite": { "name": "Lumo 2.0 Lite" } }
    }
  },
  "model": "ollama/qwen2.5-coder",
  "small_model": "ollama/qwen2.5-coder",
  "permission": { "edit": "allow", "write": "allow", "read": "allow", "bash": "allow", "webfetch": "allow", "external_directory": "allow" }
}
"@ | Set-Content -Path (Join-Path $ocDir 'opencode.json') -Encoding utf8

$agents = Join-Path $ocDir 'AGENTS.md'
if (-not (Test-Path $agents)) {
@'
# Global agent rules

## Exploring GitHub repos / URLs
When the user references a repo (URL, `owner/repo`, "look at X"), do NOT fetch web pages.
Instead: `gh repo clone owner/repo /tmp/<repo> -- --depth 1`, then explore locally with `rg`/`fd`/`cat`.
Only fetch a URL when it is genuinely not a git repo.

## Style
- Be concise; lead with the answer. Prefer editing existing files over new ones.
- No "Generated by" / co-author trailers in commits.
'@ | Set-Content -Path $agents -Encoding utf8
}

Log 'done. Next (once per machine):  cd ~\lumo-tamer ; tamer auth login'
Log 'then just run:  dormin'
