#requires -Version 5.1
# setup-opencode.ps1 — stand up the opencode coding stack on Windows.
#   opencode (Claude-Code-style TUI)  ->  ollama (local :11434)  [default]
#
# Idempotent: re-running updates configs. Prereqs (scoop/winget): opencode, ollama.
# This box runs the model server (bound to the tailscale IP so the Mac can reach it).
#
#   pwsh ~\.config\bootstrap\setup-opencode.ps1
$ErrorActionPreference = 'Stop'
function Log($m){ Write-Host "[opencode] $m" -ForegroundColor Cyan }

# 1. ensure ollama is installed + running headless
if (-not (Get-Command ollama -EA SilentlyContinue)) {
    Log 'installing ollama via winget…'
    try { winget install --id Ollama.Ollama -e --accept-source-agreements --accept-package-agreements | Out-Null }
    catch { Log 'winget install failed — install Ollama from https://ollama.com/download/windows' }
}
if (Get-Command ollama -EA SilentlyContinue) {
    $env:OLLAMA_HOST = '100.70.242.116'   # bind to the tailscale IP only (Mac reaches it, LAN does not)
    $listen = netstat -ano | Select-String ':11434' | Select-String 'LISTENING'
    if (-not $listen) { Log 'starting ollama serve headless…'; Start-Process (Get-Command ollama).Source -ArgumentList 'serve' -WindowStyle Hidden -Environment @{ OLLAMA_HOST = '100.70.242.116' } }
    else { Log 'ollama already listening' }
}

# 2. write opencode provider config + global agent rules
$ocDir = Join-Path $HOME '.config\opencode'
New-Item -ItemType Directory -Force -Path $ocDir | Out-Null
Log "writing $ocDir\opencode.json"
@"
{
  "`$schema": "https://opencode.ai/config.json",
  "provider": {
    "ollama": {
      "name": "Ollama (local)",
      "npm": "@ai-sdk/openai-compatible",
      "options": { "baseURL": "http://localhost:11434/v1", "apiKey": "ollama" },
      "models": {
        "qwen3:8b-16k": {
          "name": "Qwen 3 8B (16k, no-thinking)",
          "reasoning": false,
          "options": { "think": false },
          "limit": { "context": 16384, "output": 8192 }
        },
        "qwen3:14b": { "name": "Qwen 3 (14B)" },
        "qwen2.5-coder": { "name": "Qwen 2.5 Coder (7.6B Q4)" }
      }
    }
  },
  "model": "ollama/qwen3:8b-16k",
  "small_model": "ollama/qwen3:8b-16k",
  "permission": { "edit": "allow", "write": "allow", "read": "allow", "bash": "allow", "webfetch": "allow", "external_directory": "allow" }
}
"@ | Set-Content -Path (Join-Path $ocDir 'opencode.json') -Encoding utf8

$agents = Join-Path $ocDir 'AGENTS.md'
if (-not (Test-Path $agents)) {
@'
# Global agent rules

## Exploring GitHub repos / URLs
When the user references a repo (URL, `owner/repo`, "look at X"), do NOT fetch web pages.
Instead: `gh repo clone owner/repo /tmp/<repo> -- --depth 1`, then explore locally with `rg`/`fd`/`cat`.
Only fetch a URL when it is genuinely not a git repo.

## Style
- Be concise; lead with the answer. Prefer editing existing files over new ones.
- No "Generated by" / co-author trailers in commits.
'@ | Set-Content -Path $agents -Encoding utf8
}

Log 'done. just run:  dormin'