#!/usr/bin/env bash
# setup-opencode.sh — stand up the opencode coding stack on macOS/Linux.
#   opencode (Claude-Code-style TUI)  ->  ollama on yabohome (tailscale :11434)  [default]
#
# Idempotent: re-running updates configs. Prereqs (from Brewfile): git, opencode.
# This machine is a THIN CLIENT: the model runs on the Windows box (yabohome) and is
# reached over tailscale. Nothing is installed or downloaded here — no ollama, no
# models, no Modelfiles. That all lives on yabohome (run setup-opencode.ps1 there).
#
#   bash ~/.config/bootstrap/setup-opencode.sh
set -euo pipefail

OC_DIR="$HOME/.config/opencode"
YABOHOME="${YABOHOME:-100.70.242.116}"   # tailscale IP of the box running ollama

log() { printf '\033[36m[opencode]\033[0m %s\n' "$*"; }

command -v opencode >/dev/null || log "opencode not on PATH — install it (brew install anomalyco/tap/opencode)"

# 1. write opencode provider config + global agent rules (per-machine, not in dotfiles git)
mkdir -p "$OC_DIR"
log "writing $OC_DIR/opencode.json"
cat > "$OC_DIR/opencode.json" <<JSON
{
  "\$schema": "https://opencode.ai/config.json",
  "provider": {
    "ollama": {
      "name": "Ollama (yabohome, tailscale)",
      "npm": "@ai-sdk/openai-compatible",
      "options": { "baseURL": "http://${YABOHOME}:11434/v1", "apiKey": "ollama" },
      "models": {
        "qwen3:8b-16k": {
          "name": "Qwen 3 8B (16k, no-thinking)",
          "reasoning": false,
          "options": { "think": false },
          "limit": { "context": 16384, "output": 8192 }
        },
        "qwen3:14b": { "name": "Qwen 3 (14B)" },
        "qwen2.5-coder": { "name": "Qwen 2.5 Coder (7.6B Q4)" }
      }
    }
  },
  "model": "ollama/qwen3:8b-16k",
  "small_model": "ollama/qwen3:8b-16k",
  "permission": { "edit": "allow", "write": "allow", "read": "allow", "bash": "allow", "webfetch": "allow", "external_directory": "allow" }
}
JSON

if [ ! -f "$OC_DIR/AGENTS.md" ]; then
  log "writing $OC_DIR/AGENTS.md"
  cat > "$OC_DIR/AGENTS.md" <<'MD'
# Global agent rules

## Exploring GitHub repos / URLs
When the user references a repo (URL, `owner/repo`, "look at X"), do NOT fetch web pages.
Instead: `gh repo clone owner/repo /tmp/<repo> -- --depth 1`, then explore locally with `rg`/`fd`/`cat`.
Only fetch a URL when it is genuinely not a git repo.

## Style
- Be concise; lead with the answer. Prefer editing existing files over new ones.
- No "Generated by" / co-author trailers in commits.
MD
fi

log "done. just run:  dormin"
