#!/usr/bin/env bash
# setup-lumo.sh — stand up the Lumo coding stack on macOS/Linux.
#   opencode (Claude-Code-style TUI)  ->  lumo-tamer (local OpenAI proxy :3003)  ->  Proton Lumo
#
# Idempotent: re-running updates the build and configs but KEEPS your generated API key
# and your auth vault. Prereqs (from Brewfile): git, node, npm, go, opencode.
#
#   bash ~/.config/bootstrap/setup-lumo.sh
#   then, once per machine:  cd ~/lumo-tamer && tamer auth login
set -euo pipefail

REPO="${LUMO_TAMER_REPO:-https://github.com/ZeroTricks/lumo-tamer.git}"
DIR="$HOME/lumo-tamer"
OC_DIR="$HOME/.config/opencode"

log() { printf '\033[36m[lumo]\033[0m %s\n' "$*"; }
die() { printf '\033[31m[lumo] %s\033[0m\n' "$*" >&2; exit 1; }

for bin in git node npm go; do command -v "$bin" >/dev/null || die "missing '$bin' (install via Brewfile first)"; done

# 1. clone or update lumo-tamer
if [ -d "$DIR/.git" ]; then log "updating $DIR"; git -C "$DIR" pull --ff-only || log "pull skipped (local changes)"; else
  log "cloning lumo-tamer -> $DIR"; git clone "$REPO" "$DIR"; fi

# 2. build (TS + Go SRP auth binary) and link the global `tamer` command
log "building (npm install + build:all)…"
( cd "$DIR" && npm install --silent && npm run --silent build:all )
( cd "$DIR" && npm link >/dev/null 2>&1 ) || log "npm link skipped (use: node dist/src/tamer.js)"

# 3. reuse an existing API key if present, else generate one (never committed to git)
KEY=""
if [ -f "$DIR/config.yaml" ]; then KEY="$(grep -E '^\s*apiKey:' "$DIR/config.yaml" | head -1 | sed -E 's/.*"([^"]+)".*/\1/')"; fi
[ -n "$KEY" ] || KEY="lt-$(openssl rand -hex 24)"

# 4. write lumo-tamer config.yaml (overrides config.defaults.yaml)
log "writing $DIR/config.yaml"
cat > "$DIR/config.yaml" <<YAML
# Generated by setup-lumo.sh. Overrides config.defaults.yaml (defaults are source of truth).
auth:
  method: "login"          # Proton SRP; run once: cd ~/lumo-tamer && tamer auth login
  autoRefresh:
    enabled: true
    intervalHours: 8       # refresh before the ~12h token expiry
server:
  port: 3003
  apiKey: "$KEY"
  defaultModelTier: "auto"
  customTools:
    enabled: true          # REQUIRED so opencode's tools work through Lumo
  enableWebSearch: true
YAML

# 5. write opencode provider config + global agent rules (per-machine, not in dotfiles git)
mkdir -p "$OC_DIR"
log "writing $OC_DIR/opencode.json"
cat > "$OC_DIR/opencode.json" <<JSON
{
  "\$schema": "https://opencode.ai/config.json",
  "provider": {
    "lumo-tamer": {
      "name": "Lumo (Proton, via lumo-tamer)",
      "npm": "@ai-sdk/openai-compatible",
      "options": { "baseURL": "http://localhost:3003/v1", "apiKey": "$KEY" },
      "models": { "lumo": { "name": "Lumo (auto)" }, "lumo-max": { "name": "Lumo 2.0 Max" }, "lumo-lite": { "name": "Lumo 2.0 Lite" } }
    }
  },
  "model": "lumo-tamer/lumo",
  "permission": { "edit": "allow", "write": "allow", "read": "allow", "bash": "allow", "webfetch": "allow", "external_directory": "allow" }
}
JSON

if [ ! -f "$OC_DIR/AGENTS.md" ]; then
  log "writing $OC_DIR/AGENTS.md"
  cat > "$OC_DIR/AGENTS.md" <<'MD'
# Global agent rules

## Exploring GitHub repos / URLs
When the user references a repo (URL, `owner/repo`, "look at X"), do NOT fetch web pages.
Instead: `gh repo clone owner/repo /tmp/<repo> -- --depth 1`, then explore locally with `rg`/`fd`/`cat`.
Only fetch a URL when it is genuinely not a git repo.

## Style
- Be concise; lead with the answer. Prefer editing existing files over new ones.
- No "Generated by" / co-author trailers in commits.
MD
fi

log "done. Next (once per machine):  cd ~/lumo-tamer && tamer auth login"
log "then just run:  dormin"
